export enum errorCodes {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ERROR_GET_USERS = 'ERROR_GET_USERS',
  ERROR_GET_USER = 'ERROR_GET_USER',
  ERROR_CREATE_USER = 'ERROR_CREATE_USER',
  ERROR_LOGIN_USER = 'ERROR_LOGIN_USER',
  ERROR_GET_TEACHERS = 'ERROR_GET_TEACHERS',
  ERROR_GET_TEACHER = 'ERROR_GET_TEACHER',
  ERROR_GET_STUDENTS = 'ERROR_GET_STUDENTS',
  ERROR_GET_STUDENT = 'ERROR_GET_STUDENT',
  ERROR_ID_NAN = 'ERROR_ID_IS_NAN'
}
