export enum errorCodes {
  // * Server
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  // * Users
  ERROR_GET_USERS = 'ERROR_GET_USERS',
  ERROR_GET_USER = 'ERROR_GET_USER',
  ERROR_CREATE_USER = 'ERROR_CREATE_USER',
  ERROR_LOGIN_USER = 'ERROR_LOGIN_USER',
  // * Teachers
  ERROR_GET_TEACHERS = 'ERROR_GET_TEACHERS',
  ERROR_GET_TEACHER = 'ERROR_GET_TEACHER',
  ERROR_GET_STUDENT = 'ERROR_GET_STUDENT',
  // * ID
  ERROR_ID_NAN = 'ERROR_ID_IS_NAN',
  // * Number
  ERROR_NUMBER_NAN = 'ERROR_NUMBER_IS_NAN',
  // * Roles
  ERROR_CREATE_ROLE = 'ERROR_CREATE_ROLE',
  // * Classes
  ERROR_GET_CLASSES = 'ERROR_GET_CLASSES',
  ERROR_GET_CLASS = 'ERROR_GET_CLASS',
  ERROR_CREATE_CLASS = 'ERROR_CREATE_CLASS',
  ERROR_EDIT_CLASS = 'ERROR_EDIT_CLASS',
  // * Students
  ERROR_CREATE_STUDENT = 'ERROR_CREATE_STUDENT',
  ERROR_GET_STUDENTS = 'ERROR_GET_STUDENTS',
}
